export const Data=  [
    {
      id: 1,
      name: "JavaScript",
      bugCount: 3,
      bugs: [
        {
          id: 1,
          title: "Async/await not working in forEach loop",
          caption: "Async inside forEach doesn’t wait for promises to resolve.",
          votes: 312,
          replies: 14,
          replyDetails: [
            {
              replier: "Omar",
              email: "omar@example.com",
              time: "1 hour ago",
              content:
                "Use a for...of loop instead of forEach with async/await.",
              likesCount: 2,
            },
            {
              replier: "Laila",
              email: "laila@example.com",
              time: "30 mins ago",
              content: "Exactly, forEach doesn’t handle promises correctly.",
              likesCount: 5,
            },
          ],
          views: 2456,
          date: "1 week ago",
          state: "solved",
          tags: ["Async", "Promises"],
          author: "Tom Anderson",
          sort: "trending",
        },
        {
          id: 2,
          title: "Cannot read property of undefined error",
          caption: "Accessing a property of an undefined variable.",
          votes: 278,
          replies: 11,
          replyDetails: [
            {
              replier: "Hassan",
              email: "hassan@example.com",
              time: "2 hours ago",
              content:
                "You should check for null or undefined before accessing properties.",
              likesCount: 3,
            },
          ],
          views: 1890,
          date: "3 days ago",
          state: "unsolved",
          tags: ["TypeError", "DOM"],
          author: "Lara Smith",
          sort: "votes",
        },
        {
          id: 3,
          title: "Event listener memory leak in React",
          caption: "Listeners not removed properly cause memory leaks.",
          votes: 189,
          replies: 9,
          replyDetails: [
            {
              replier: "Khaled",
              email: "khaled@example.com",
              time: "5 hours ago",
              content: "Remember to remove listeners in useEffect cleanup.",
              likesCount: 1,
            },
          ],
          views: 1678,
          date: "2 weeks ago",
          state: "solved",
          tags: ["React", "Performance"],
          author: "John Adams",
          sort: "recent",
        },
      ],
    },
    {
      id: 2,
      name: "Python",
      bugCount: 2890,
      bugs: [
        {
          id: 1,
          title: "ImportError: No module named 'requests'",
          caption:
            "Occurs when the required library isn’t installed or imported.",
          votes: 321,
          replies: 18,
          replyDetails: [
            {
              replier: "Noor",
              email: "noor@example.com",
              time: "4 hours ago",
              content: "Run `pip install requests` to fix this issue.",
              likesCount: 4,
            },
          ],
          views: 2100,
          date: "4 days ago",
          state: "solved",
          tags: ["Import", "Modules"],
          author: "Nora Wilson",
          sort: "recent",
        },
        {
          id: 2,
          title: "IndentationError in multi-line statement",
          caption: "Misaligned indentation breaks Python’s structure.",
          votes: 276,
          replies: 12,
          replyDetails: [
            {
              replier: "Yasmin",
              email: "yasmin@example.com",
              time: "2 days ago",
              content:
                "Check spaces vs tabs — Python is strict about indentation.",
              likesCount: 2,
            },
          ],
          views: 1780,
          date: "2 weeks ago",
          state: "unsolved",
          tags: ["Syntax", "Indentation"],
          author: "Alex Carter",
          sort: "trending",
        },
      ],
    },
    {
      id: 3,
      name: "React",
      bugCount: 4125,
      bugs: [
        {
          id: 1,
          title: "useState not updating immediately after setState",
          caption: "React state updates are asynchronous by design.",
          votes: 412,
          replies: 20,
          replyDetails: [
            {
              replier: "Heba",
              email: "heba@example.com",
              time: "1 day ago",
              content: "Use useEffect if you need to respond to state changes.",
              likesCount: 6,
            },
          ],
          views: 2500,
          date: "2 days ago",
          state: "solved",
          tags: ["Hooks", "State"],
          author: "Evan Stone",
          sort: "votes",
        },
        {
          id: 2,
          title: "Infinite re-render loop with useEffect",
          caption: "Dependencies missing in useEffect cause re-render loops.",
          votes: 386,
          replies: 17,
          replyDetails: [
            {
              replier: "Ahmed",
              email: "ahmed@example.com",
              time: "3 hours ago",
              content:
                "Always add dependencies to the useEffect dependency array.",
              likesCount: 3,
            },
          ],
          views: 2300,
          date: "1 week ago",
          state: "unsolved",
          tags: ["useEffect", "Rendering"],
          author: "Hannah Lee",
          sort: "recent",
        },
      ],
    },
    {
      id: 4,
      name: "TypeScript",
      bugCount: 2134,
      bugs: [
        {
          id: 1,
          title: "Type 'null' is not assignable to type",
          caption: "Occurs when strict null checks are enabled.",
          votes: 275,
          replies: 10,
          replyDetails: [
            {
              replier: "Lina",
              email: "lina@example.com",
              time: "6 hours ago",
              content: "Add `| null` to your type or disable strictNullChecks.",
              likesCount: 2,
            },
          ],
          views: 1400,
          date: "1 day ago",
          state: "unsolved",
          tags: ["Types", "Strict Mode"],
          author: "Chloe White",
          sort: "recent",
        },
        {
          id: 2,
          title: "Cannot find module or its type declarations",
          caption: "Missing or misconfigured @types package.",
          votes: 242,
          replies: 9,
          replyDetails: [
            {
              replier: "Karim",
              email: "karim@example.com",
              time: "8 hours ago",
              content: "Install the missing `@types` package for that module.",
              likesCount: 1,
            },
          ],
          views: 1180,
          date: "3 days ago",
          state: "solved",
          tags: ["Modules", "Declarations"],
          author: "Ryan Brooks",
          sort: "votes",
        },
      ],
    },
    {
      id: 5,
      name: "CSS/Tailwind",
      bugCount: 1876,
      bugs: [
        {
          id: 1,
          title: "Flexbox not centering items vertically",
          caption: "Occurs due to missing align-items or height rules.",
          votes: 330,
          replies: 15,
          replyDetails: [
            {
              replier: "Ola",
              email: "ola@example.com",
              time: "5 hours ago",
              content: "Add `align-items: center` to the flex container.",
              likesCount: 2,
            },
          ],
          views: 2100,
          date: "5 days ago",
          state: "solved",
          tags: ["Flexbox", "Layout"],
          author: "Mia Johnson",
          sort: "votes",
        },
        {
          id: 2,
          title: "Tailwind classes not applying in production",
          caption: "PurgeCSS removes unused classes unexpectedly.",
          votes: 276,
          replies: 12,
          replyDetails: [
            {
              replier: "Ali",
              email: "ali@example.com",
              time: "1 day ago",
              content:
                "Add your dynamic classes to the safelist in tailwind.config.js.",
              likesCount: 3,
            },
          ],
          views: 1800,
          date: "2 weeks ago",
          state: "unsolved",
          tags: ["Tailwind", "Build"],
          author: "Daniel Reed",
          sort: "recent",
        },
      ],
    },
    {
      id: 6,
      name: "Node.js",
      bugCount: 2456,
      bugs: [
        {
          id: 1,
          title: "EADDRINUSE: Port already in use",
          caption: "Occurs when trying to bind to a port already in use.",
          votes: 389,
          replies: 16,
          replyDetails: [
            {
              replier: "Sara",
              email: "sara@example.com",
              time: "2 hours ago",
              content: "Use a different port or stop the process using it.",
              likesCount: 2,
            },
          ],
          views: 2300,
          date: "3 days ago",
          state: "solved",
          tags: ["Server", "Ports"],
          author: "James Miller",
          sort: "recent",
        },
        {
          id: 2,
          title: "MongoDB connection timeout error",
          caption: "Connection string or network issue with MongoDB.",
          votes: 312,
          replies: 13,
          replyDetails: [
            {
              replier: "Mahmoud",
              email: "mahmoud@example.com",
              time: "5 hours ago",
              content:
                "Check your MongoDB URI and ensure the server is running.",
              likesCount: 4,
            },
          ],
          views: 2100,
          date: "1 week ago",
          state: "unsolved",
          tags: ["MongoDB", "Database"],
          author: "Ella Brown",
          sort: "trending",
        },
      ],
    },
    {
      id: 7,
      name: "C++",
      bugCount: 1654,
      bugs: [
        {
          id: 1,
          title: "Segmentation fault in pointer arithmetic",
          caption: "Occurs when accessing memory outside valid range.",
          votes: 267,
          replies: 10,
          replyDetails: [
            {
              replier: "Youssef",
              email: "youssef@example.com",
              time: "9 hours ago",
              content: "Always validate pointer bounds before dereferencing.",
              likesCount: 1,
            },
          ],
          views: 1500,
          date: "1 day ago",
          state: "unsolved",
          tags: ["Pointers", "Memory"],
          author: "David King",
          sort: "trending",
        },
      ],
    },
    {
      id: 8,
      name: "Java",
      bugCount: 1923,
      bugs: [
        {
          id: 1,
          title: "NullPointerException in stream operation",
          caption: "Occurs when stream operates on a null reference.",
          votes: 298,
          replies: 14,
          replyDetails: [
            {
              replier: "Rana",
              email: "rana@example.com",
              time: "7 hours ago",
              content:
                "Ensure your collection isn’t null before calling stream().",
              likesCount: 3,
            },
          ],
          views: 1600,
          date: "4 days ago",
          state: "solved",
          tags: ["Streams", "Exceptions"],
          author: "Nina Patel",
          sort: "votes",
        },
      ],
    },
    {
      id: 9,
      name: "HTML",
      bugCount: 954,
      bugs: [
        {
          id: 1,
          title: "Image not showing on page",
          caption: "Broken path or missing alt attribute.",
          votes: 150,
          replies: 5,
          replyDetails: [
            {
              replier: "Ziad",
              email: "ziad@example.com",
              time: "2 hours ago",
              content:
                "Check your image path — it’s usually a relative path issue.",
              likesCount: 1,
            },
          ],
          views: 800,
          date: "6 days ago",
          state: "solved",
          tags: ["Images", "Paths"],
          author: "Owen Baker",
          sort: "recent",
        },
      ],
    },
    {
      id: 10,
      name: "SQL",
      bugCount: 1350,
      bugs: [
        {
          id: 1,
          title: "SQL syntax error near keyword",
          caption: "Occurs when reserved keywords are misused.",
          votes: 199,
          replies: 7,
          replyDetails: [
            {
              replier: "Layla",
              email: "layla@example.com",
              time: "1 day ago",
              content: "Try enclosing column names with backticks or brackets.",
              likesCount: 2,
            },
          ],
          views: 950,
          date: "5 days ago",
          state: "unsolved",
          tags: ["Syntax", "Query"],
          author: "Ben Carter",
          sort: "votes",
        },
      ],
    },
  ];